projects:
  users-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: sisisazbuffmzcwn3jpzrcxc64
        maxDepth: 2
extensions:
  amplify:
    version: 3
